name: xcode bundle
on: workflow_dispatch
jobs:
  build:
    name: Xcode bundle
    runs-on: macos-10.15
    steps:
      - name: Configure macOS runner
        run: |
          brew install --cask powershell

      - name: Copy macOS SDK
        run: |
          XCODE_DEVELOPER_PATH=$(xcode-select -p)
          XCODE_PLATFORMS_PATH="$XCODE_DEVELOPER_PATH/Platforms"

          PLATFORM_NAME=MacOSX
          PLATFORM_PATH="$XCODE_PLATFORMS_PATH/$PLATFORM_NAME.platform"
          PLATFORM_SDK_PATH="$PLATFORM_PATH/Developer/SDKs/$PLATFORM_NAME.sdk"

          function rreadlink()
          {
            if [ ! -h "$1" ]; then
              echo "$1"
            else
              local link="$(expr "$(command ls -ld -- "$1")" : '.*-> \(.*\)$')"
              cd $(dirname $1)
              rreadlink "$link" | sed "s|^\([^/].*\)\$|$(dirname $1)/\1|"
            fi
          }

          mkdir -p xcode-bundle
          cp -r $(rreadlink $PLATFORM_SDK_PATH) "xcode-bundle/$PLATFORM_NAME.sdk" &>/dev/null

      - name: Copy iOS SDK
        run: |
          XCODE_DEVELOPER_PATH=$(xcode-select -p)
          XCODE_PLATFORMS_PATH="$XCODE_DEVELOPER_PATH/Platforms"

          PLATFORM_NAME=iPhoneOS
          PLATFORM_PATH="$XCODE_PLATFORMS_PATH/$PLATFORM_NAME.platform"
          PLATFORM_SDK_PATH="$PLATFORM_PATH/Developer/SDKs/$PLATFORM_NAME.sdk"

          mkdir -p xcode-bundle
          cp -r $PLATFORM_SDK_PATH xcode-bundle/

      - name: Copy Xcode toolchain
        shell: pwsh
        run: |
          $XcodeDeveloperPath = $(xcode-select -p)
          $XcodePlatformsPath = Join-Path $XcodeDeveloperPath "Platforms"

          $BundlePath = Join-Path $Env:GITHUB_WORKSPACE "xcode-bundle"
          New-Item -Path $BundlePath -ItemType Directory | Out-Null

          Write-Host "Copying Xcode xctoolchain"
          $XcodeToolchainsPath = Join-Path $XcodeDeveloperPath "Toolchains"
          $XcodeToolchainPath = Join-Path $XcodeToolchainsPath "XcodeDefault.xctoolchain"
          $DestinationPath = Join-Path $BundlePath "XcodeDefault.xctoolchain"
          New-Item -Path $DestinationPath -ItemType Directory | Out-Null
          cp -r "$XcodeToolchainPath\usr\include" "$DestinationPath\usr\include"
          cp -r "$XcodeToolchainPath\usr\lib" "$DestinationPath\usr\lib"

      - name: Package Xcode bundle
        shell: pwsh
        run: |
          tar -cJf xcode-bundle.tar.xz xcode-bundle

      - name: Upload xcode-bundle package
        uses: actions/upload-artifact@v2
        with:
          name: xcode-bundle
          path: xcode-bundle.tar.xz
